theme: jekyll-theme-cayman

title: [Herramientas para la Enseñanza de las Matemáticas]
description: [Este repositorio está diseñado para el taller sobre enseñanza de las matemáticas usando Jupyter Notebook Slides y GitHub Pages.]
show_downloads: true

