theme: jekyll-theme-cayman

title: [Herramienta para la Enseñanza de las Matemáticas]
description: [Este repositorio esta diseñado para el taller sobre enseñanza de las matemátias usando Jupyter Notebook Slides y GitHub Pages.]
show_downloads: true

